function [H_h,H_sh,dH_s] = helsG(rho,c,k,r_ms,r_lh,n_ma)
    phi_s = r_ms(:,1);
    theta_s = r_ms(:,2);
    r_sp = r_ms(:,3);
    phi_h = r_lh(:,1);
    theta_h = r_lh(:,2);
    r_hp = r_lh(:,3);
    m = size(phi_s,1);
    l = size(phi_h,1);
    t = gpuArray(cell2mat(arrayfun(@(x) sort(abs(-x:1:x)).*((-ones(1,((x*2)+1))).^(0:(((x*2)+1)-1))),0:n_ma,'UniformOutput',false)));
    t1 = t(t>=0);
    m_v = gpuArray(cell2mat(arrayfun(@(x) ones(1,((x*2)+1))*x,0:n_ma,'UniformOutput',false)));
    m_v1 = m_v(t>=0);
    fbj = besselnjG(n_ma,k*r_sp);
    fby = besselnyG(n_ma,k*r_sp);
    jn = sqrt(pi./(2*k*r_sp)).*fbj;
    yn = sqrt(pi./(2*k*r_sp)).*fby;
    fbjd1 = dbesselnjG(n_ma,k*r_sp);
    fbyd1 = dbesselnyG(n_ma,k*r_sp);
    djn =  sqrt(pi/2)*k*((1./(k*r_sp)).^(3/2)).*((m_v.*fbj)-((k*r_sp).*fbjd1));
    dyn =  sqrt(pi/2)*k*((1./(k*r_sp)).^(3/2)).*((m_v.*fby)-((k*r_sp).*fbyd1));
    fbjfp = besselnjG(n_ma,k*r_hp);
    fbyfp = besselnyG(n_ma,k*r_hp);
    jnfp = sqrt(pi./(2*k*r_hp)).*fbjfp;
    ynfp = sqrt(pi./(2*k*r_hp)).*fbyfp;
    hH_ks = djn+1i*dyn;
    H_ks = jn+1i*yn;
    H_kh = jnfp+1i*ynfp;
    m2c = find(t>0);
    idx = find(t>=0);
    L_ts = ((-1).^t1).*((1-cos(theta_s).^2).^(t1./2)).*(factorial(2*t1)./((2.^t1).*factorial(t1))).*gegenbauerG(m_v1-t1,t1+(1/2),cos(theta_s),n_ma);
    L_th = ((-1).^t1).*((1-cos(theta_h).^2).^(t1./2)).*(factorial(2*t1)./((2.^t1).*factorial(t1))).*gegenbauerG(m_v1-t1,t1+(1/2),cos(theta_h),n_ma);
    P_ls = gpuArray.zeros(m,length(t));
    P_ls(:,idx) = sqrt(((2*m_v1+1).*factorial(m_v1-t1))./((4*pi)*factorial(m_v1+t1))).*L_ts.*exp(1i*t1.*phi_s);
    P_ls(:,m2c-1) = ((-1).^(t(m2c))).*conj(P_ls(:,m2c));
    P_lh = gpuArray.zeros(l,length(t));
    P_lh(:,idx) = sqrt(((2*m_v1+1).*factorial(m_v1-t1))./((4*pi)*factorial(m_v1+t1))).*L_th.*exp(1i*t1.*phi_h);
    P_lh(:,m2c-1) = ((-1).^(t(m2c))).*conj(P_lh(:,m2c));
    dH_s = ((1/(1i*rho*c*k))*hH_ks).*P_ls;
    H_sh = H_ks.*P_ls;
    H_h = H_kh.*P_lh;
end